#!/bin/bash
# To run under Linux, use:
# chmod 755 compile_c
gcc -c -fpic myeunumber.c -lm
gcc -shared -o libeunumber.so myeunumber.o -lm
gcc -L$PWD -Wall -o test eunumer_c.c -leunumber -lm
# export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
./test
